on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: check-out code
        uses: actions/checkout@v3
        with:
          node-version: '22'
    
      - name: install depedencies
        run: npm install

      - name: run unit tests
        env: 
          MONGO_URI: " mongodb://0.0.0.0:27017/marvel-guerra-dos-reinos"
        run: npm test
